/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/water-bottle.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/water-bottle.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.WaterBottle.geometry} material={materials.BottleMat} rotation={[-Math.PI, 0, -Math.PI]} />
    </group>
  )
}

useGLTF.preload('/water-bottle.glb')
